[package]
name = "my_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-cors="0.7.0"
dotenv="0.15"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
actix-rt="2.2"